// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Catalogo_Pecas.Models
{
    public partial class Clientes
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(60)]
        public string Nome { get; set; }
        [Required]
        [StringLength(60)]
        public string Email { get; set; }
        [Required]
        [Column("cPF")]
        [StringLength(14)]
        public string CPf { get; set; }
        [Required]
        [StringLength(12)]
        public string Telefone { get; set; }
        [Required]
        [StringLength(60)]
        public string Cidade { get; set; }
        [StringLength(200)]
        public string Msg { get; set; }
    }
}